/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ItemEntity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItemEntity__factory>;
    getContractFactory(
      name: "ListContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListContract__factory>;
    getContractFactory(
      name: "MappedStructs",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MappedStructs__factory>;
    getContractFactory(
      name: "Zoom",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Zoom__factory>;
    getContractFactory(
      name: "Zoom2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Zoom2__factory>;
    getContractFactory(
      name: "Zoom3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Zoom3__factory>;
    getContractFactory(
      name: "Zoom4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Zoom4__factory>;

    getContractAt(
      name: "ItemEntity",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItemEntity>;
    getContractAt(
      name: "ListContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ListContract>;
    getContractAt(
      name: "MappedStructs",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MappedStructs>;
    getContractAt(
      name: "Zoom",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Zoom>;
    getContractAt(
      name: "Zoom2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Zoom2>;
    getContractAt(
      name: "Zoom3",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Zoom3>;
    getContractAt(
      name: "Zoom4",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Zoom4>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
